### ISSUE TITLE
program_change not taking effect in the first second of midi file

### ISSUE THREAD

**Issue by happyTonakai** [nwhitehead/pyfluidsynth#72] opened 2024-08-06 08:22 UTC
I want to change the program after loading a midi file, but it seems not working as expected:
```py
import fluidsynth
import numpy
import pyaudio

pa = pyaudio.PyAudio()
strm = pa.open(format=pyaudio.paInt16, channels=2, rate=44100, output=True)

fs = fluidsynth.Synth()
sfid = fs.sfload("FluidR3_GM.sf2")
fs.play_midi_file("1080-c01.mid")
fs.program_select(0, sfid, 0, 0)

for ch in range(16):
    fs.program_change(ch, 0)  # change programs to piano not working
    fs.pitch_bend(ch, 8192)  # pitch shifting works fine
    fs.cc(ch, 91, 127)  # reverb control works fine

# Generate 10 seconds of audio into s
s = []
for _ in range(10):
    s = numpy.append(s, fs.get_samples(44100))
    if fluidsynth.fluid_player_get_status(fs.player) != fluidsynth.FLUID_PLAYER_PLAYING:
        break

fs.delete()

samps = fluidsynth.raw_audio_string(s)
strm.write(samps)
```

The `pitch_bend` and `cc` both work, but `program_change` is not. Moving the `program_change` into the for loop as following works well except the first second still remaining unchanged.
```py
for _ in range(20):
    for c in range(16):
        fs.program_change(c, 0)
    s = numpy.append(s, fs.get_samples(44100))
    if fluidsynth.fluid_player_get_status(fs.player) != fluidsynth.FLUID_PLAYER_PLAYING:
        break
```

Finally I have to generate and ignore the first second audio samples:
```py
fs.get_samples(44100)  # get and ignore the first second
for ch in range(16):
    fs.program_change(ch, 0)  # working now

# Generate 10 seconds of audio into s
s = []
for _ in range(10):
    s = numpy.append(s, fs.get_samples(44100))
    if fluidsynth.fluid_player_get_status(fs.player) != fluidsynth.FLUID_PLAYER_PLAYING:
        break
```

I don't know what is going on. Getting samples shorter than 1 second in advance will not work.

**Comment by happyTonakai** [comment] 2024-08-06 09:14
It seems that `get_samples` will overwrite the program setting. Before `program_change` and `get_samples`, I cannot use `fs.channel_info(0)` which raises OSError:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Users\HanZR\AppData\Local\Programs\Python\Python311\Lib\site-packages\fluidsynth.py", line 768, in channel_info
    presetname = self.sfpreset_name(sfontid, banknum, presetnum)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HanZR\AppData\Local\Programs\Python\Python311\Lib\site-packages\fluidsynth.py", line 785, in sfpreset_name
    preset=fluid_sfont_get_preset(sfont, bank, prenum)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation reading 0x0000000000000028
```

After calling `program_change` it is able to call `channel_info`, but the info changes right after `get_samples` (longer than 1 second).
```py
fs.program_change(0, 19)
>> 0
fs.channel_info(0)
>> (1, 0, 19, 'Church Organ')
fs.get_samples(samplerate)
>> array([ 0,  0,  0, ...,  1,  1, -1], dtype=int16)
fs.channel_info(0)
>> (1, 0, 38, 'Synth Bass 1')
```

**Comment by happyTonakai** [comment] 2024-08-07 02:52
I found another issue related to `program_change`. It doesn't take effect when the channel has program change events later.

The `1080-c01.mid` for test has no program change events except at the beginning, so this midi file has no problem:
```
Track 1: String Quartet
Time: 0, Channel: 0, Program Number: 40, Program Name: Violin
Track 2: --------------------------------------
Time: 0, Channel: 1, Program Number: 40, Program Name: Violin
Track 3: Johann Sebastian Bach  (1685-1750)
Time: 0, Channel: 2, Program Number: 41, Program Name: Viola
Track 4: The Art of Fugue - BWV 1080
Time: 0, Channel: 3, Program Number: 42, Program Name: Cello
```

But another midi has many program change events after the beginning as following:
```
Track 1:
Time: 98, Channel: 0, Program Number: 38, Program Name: Synth Bass 1
Track 2:
Time: 102, Channel: 1, Program Number: 25, Program Name: Acoustic Guitar (steel)
Time: 0, Channel: 1, Program Number: 90, Program Name: Pad 3 (polysynth)
Track 3:
Time: 107, Channel: 2, Program Number: 25, Program Name: Acoustic Guitar (steel)
Track 4:
Time: 112, Channel: 3, Program Number: 1, Program Name: Bright Acoustic Piano
Time: 0, Channel: 3, Program Number: 50, Program Name: SynthStrings 1
Track 5:
Time: 117, Channel: 4, Program Number: 33, Program Name: Electric Bass (finger)
Time: 25, Channel: 4, Program Number: 39, Program Name: Synth Bass 2
Track 6:
Time: 123, Channel: 5, Program Number: 0, Program Name: Acoustic Grand Piano
Track 7:
Time: 143, Channel: 9, Program Number: 0, Program Name: Acoustic Grand Piano
```

I think these two issues may be related and a same way out is something like [filtering midi events](https://nwhitehead.github.io/tinysoundfont-pybind/guide.html#filter-midi-events) in tinysoundfont. I'm wondering if it is possible to do something similar with pyfluidsynth.

**Comment by nwhitehead** [comment] 2024-08-07 18:58
I think the root issue is that MIDI has state. Playing back MIDI songs includes commands to update parts of the state at different times. So if you try to do a program change yourself it might be overwritten by the MIDI song as it starts playing.

As far as I can tell FluidSynth is working as expected in this scenario. I don't know of any MIDI event filtering mechanism within FluidSynth itself that would do what you want.

FluidSynth does have a complicated rule system for MIDI routing, I don't really know how it works. According to the [documentation](https://www.fluidsynth.org/api/MIDIRouter.html) it only works for actual MIDI events and not MIDI events from the MIDI player so it probably won't help unfortunately.

I see two possible ways to proceed. One way would be to change the MIDI file itself and let FluidSynth play the MIDI file. There are many Python libraries for reading/writing MIDI. You could filter/modify things as you want, then write out the updated version to a temp file and play it.

The other way would be to use FluidSynth as a MIDI event player. Parse and interpret the MIDI events from Python then call the various functions in FluidSynth at the right times. This way gives you a lot of control but takes some coding (and dealing with timing information).

Anyway closing this as not a bug, feel free to reopen if I'm missing something.

**Closed by nwhitehead** 2024-08-07 18:58 UTC
